export const Apiurl = "http://localhost:3000/";
export const ApiLogin = "v1/public/client/user/login";
export const ApiRegistro = "v1/public/client/user/register";
export const ApiWhoami = "v1/client/user/whoami";
export const ApiContact = 'v1/client/contact';
export const ApiContactList = 'v1/client/contact?alias=';
export const ApiBalance = 'v1/client/user/balance';
export const ApiAccount = 'v1/client/user/account/:account_number';
export const ApiMovement = 'v1/client/movement';
export const ApiMovimientos = 'v1/client/movement?page=1&page_size=20&multiplier=1';
export const ApiContactId= 'v1/client/contact/';
export const ApiContrasenna= 'v1/client/user/password';
